modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="hk400test"
version="0.0.1"
displayName="Henkiller400 Co-Op Test"
credits="ToDo: add credits"
displayURL="https://weside-in/future.ok/?"
authors="Carslo45, Henkiller400"
description='''
ToDo: add Description
'''

[[dependencies.hk400test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.hk400test]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hk400test]]
    modId="curios"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hk400test]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

