modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="hk400test"
version="1.0.1"
displayName="Henkiller400 Co-Op Test"
credits="ToDo: add credits"
displayURL="https://weside-in/future.ok"
authors="Carslo45, Henkiller400"
description='''
ToDo: add Description
'''

[[dependencies.hk400test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




